module Aoc23
  module Cli
    class ArgDef
      def initialize: (name: String, description: String?, cls: String) -> void

      attr_reader name: String
      attr_reader description: String?
      attr_reader cls: String
    end
  end
end
