module Aoc23
  module Cli
    class ArgDefs
      @items: Array[ArgDef]
      @items_by_name: Hash[String, ArgDef]

      def initialize: (*ArgDef) -> void
      def get: (Integer) -> ArgDef
      def fetch: (String) -> ArgDef

      def self.from_a: (Array[ArgDef]) -> instance

      attr_reader items: Array[ArgDef]
    end
  end
end
