module Aoc23
  module Cli
    class OptionDefs
      @option_defs: Array[OptionDef]
      @option_defs_by_name: Hash[String, OptionDef]

      def initialize: (*OptionDef) -> void

      def self.from_a: (Array[OptionDef]) -> instance

      def fetch: (String) -> OptionDef

      include Enumerable[class]
    end
  end
end
